### ISSUE TITLE
Misplaced Player Spawn Point on the Example Map

### ISSUE THREAD

**Issue by HeadClot** [DaveFace/CheekyFPS#1]
Hey @DaveFace, 
The player spawn point is inside world geometry and that causes clipping issues when the player spawns.

I have since fixed this on my end. But this may confuse users who are new to unreal engine 4.

**Comment by DaveFace** [comment]
Yes I spotted this when I rebased the project earlier, it's fixed in the most recent update. Guess I've gotten to used to having the player start at camera location. Cheers for the heads up
